In [62]:
!pip install nba_api

Requirement already satisfied: nba_api in /opt/conda/lib/python3.10/site-packages (1.5.2)
Requirement already satisfied: certifi<2025.0.0,>=2023.7.22 in /opt/conda/lib/python3.10/site-packages (from nba_api) (2024.7.4)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /opt/conda/lib/python3.10/site-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.31.2 in /opt/conda/lib/python3.10/site-packages (from nba_api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests<3.0.0,>=2.31.2->nba_api) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests<3.0.0,>=2.31.2->nba_api) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests<3.0.0,>=2.31.2->nba_api) (1.26.18)

In [63]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
pd.options.display.max_columns = None
pd.options.display.max_rows = 91

# Import the DataFrame with all of LeBron's games played in the last 10 seasons

In [152]:
# all_games_df = pd.read_csv('/kaggle/input/final-statistics-97000-x-157/allplayerstatistics.csv')
all_games_df = pd.read_csv('/kaggle/input/almost-last-10-seasons/almostLastTenSeasons.csv')
all_games_df

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,YEAR,TEAM,RIVAL,AWAY,TEAM_ID,RIVAL_ID,TEAM_NAME,TEAM_W_PCT,TEAM_GP_RANK,TEAM_W_RANK,TEAM_L_RANK,TEAM_W_PCT_RANK,TEAM_MIN_RANK,TEAM_FGM_RANK,TEAM_FGA_RANK,TEAM_FG_PCT_RANK,TEAM_FG3M_RANK,TEAM_FG3A_RANK,TEAM_FG3_PCT_RANK,TEAM_FTM_RANK,TEAM_FTA_RANK,TEAM_FT_PCT_RANK,TEAM_OREB_RANK,TEAM_DREB_RANK,TEAM_REB_RANK,TEAM_AST_RANK,TEAM_TOV_RANK,TEAM_STL_RANK,TEAM_BLK_RANK,TEAM_BLKA_RANK,TEAM_PF_RANK,TEAM_PFD_RANK,TEAM_PTS_RANK,TEAM_PLUS_MINUS_RANK,TEAM_SEASON,RIVAL_TEAM_ID,RIVAL_NAME,RIVAL_W_PCT,RIVAL_GP_RANK,RIVAL_W_RANK,RIVAL_L_RANK,RIVAL_W_PCT_RANK,RIVAL_MIN_RANK,RIVAL_FGM_RANK,RIVAL_FGA_RANK,RIVAL_FG_PCT_RANK,RIVAL_FG3M_RANK,RIVAL_FG3A_RANK,RIVAL_FG3_PCT_RANK,RIVAL_FTM_RANK,RIVAL_FTA_RANK,RIVAL_FT_PCT_RANK,RIVAL_OREB_RANK,RIVAL_DREB_RANK,RIVAL_REB_RANK,RIVAL_AST_RANK,RIVAL_TOV_RANK,RIVAL_STL_RANK,RIVAL_BLK_RANK,RIVAL_BLKA_RANK,RIVAL_PF_RANK,RIVAL_PFD_RANK,RIVAL_PTS_RANK,RIVAL_PLUS_MINUS_RANK,RIVAL_SEASON
0,22023,1630173,22301190,"APR 14, 2024",W,19,2,3,0.667,0,0,0.000,0,0,0.0,1,4,5,2,0,1,2,3,4,-2,1,2024,NYK,CHI,False,1610612752,1610612741,New York Knicks,0.610,1.0,6.0,6.0,6.0,23.0,22.0,18.0,20.0,10.0,13.0,14.0,16.0,14.0,16.0,1.0,21.0,5.0,29.0,15.0,17.0,29.0,20.0,6.0,10.0,19.0,5.0,2023-24,1.610613e+09,Chicago Bulls,0.476,1.0,20.0,20.0,20.0,1.0,16.0,13.0,18.0,27.0,26.0,20.0,17.0,18.0,10.0,8.0,19.0,14.0,23.0,3.0,9.0,18.0,14.0,17.0,14.0,22.0,20.0,2023-24
1,22023,1630173,22301175,"APR 12, 2024",W,8,2,2,1.000,1,1,1.000,0,0,0.0,0,3,3,0,0,0,0,0,5,3,1,2024,NYK,BKN,False,1610612752,1610612751,New York Knicks,0.610,1.0,6.0,6.0,6.0,23.0,22.0,18.0,20.0,10.0,13.0,14.0,16.0,14.0,16.0,1.0,21.0,5.0,29.0,15.0,17.0,29.0,20.0,6.0,10.0,19.0,5.0,2023-24,1.610613e+09,Brooklyn Nets,0.390,1.0,22.0,22.0,22.0,10.0,25.0,16.0,28.0,9.0,9.0,19.0,23.0,20.0,28.0,7.0,20.0,11.0,20.0,12.0,28.0,12.0,16.0,13.0,21.0,25.0,22.0,2023-24
2,22023,1630173,22301167,"APR 11, 2024",W,16,1,6,0.167,0,1,0.000,0,0,0.0,2,3,5,0,0,1,1,0,2,-9,1,2024,NYK,BOS,True,1610612752,1610612738,New York Knicks,0.610,1.0,6.0,6.0,6.0,23.0,22.0,18.0,20.0,10.0,13.0,14.0,16.0,14.0,16.0,1.0,21.0,5.0,29.0,15.0,17.0,29.0,20.0,6.0,10.0,19.0,5.0,2023-24,1.610613e+09,Boston Celtics,0.780,1.0,1.0,1.0,1.0,7.0,4.0,8.0,8.0,1.0,1.0,2.0,19.0,26.0,7.0,14.0,1.0,2.0,14.0,1.0,27.0,1.0,1.0,2.0,30.0,2.0,1.0,2023-24
3,22023,1630173,22301139,"APR 07, 2024",W,5,0,1,0.000,0,0,0.000,0,0,0.0,0,0,0,0,0,0,0,1,0,5,1,2024,NYK,MIL,True,1610612752,1610612749,New York Knicks,0.610,1.0,6.0,6.0,6.0,23.0,22.0,18.0,20.0,10.0,13.0,14.0,16.0,14.0,16.0,1.0,21.0,5.0,29.0,15.0,17.0,29.0,20.0,6.0,10.0,19.0,5.0,2023-24,1.610613e+09,Milwaukee Bucks,0.598,1.0,8.0,8.0,8.0,10.0,8.0,19.0,7.0,5.0,5.0,11.0,7.0,3.0,19.0,24.0,3.0,9.0,17.0,9.0,26.0,15.0,3.0,21.0,9.0,4.0,11.0,2023-24
4,22023,1630173,22301119,"APR 05, 2024",L,19,0,2,0.000,0,1,0.000,0,0,0.0,1,3,4,1,1,0,1,4,0,-2,1,2024,NYK,CHI,True,1610612752,1610612741,New York Knicks,0.610,1.0,6.0,6.0,6.0,23.0,22.0,18.0,20.0,10.0,13.0,14.0,16.0,14.0,16.0,1.0,21.0,5.0,29.0,15.0,17.0,29.0,20.0,6.0,10.0,19.0,5.0,2023-24,1.610613e+09,Chicago Bulls,0.476,1.0,20.0,20.0,20.0,1.0,16.0,13.0,18.0,27.0,26.0,20.0,17.0,18.0,10.0,8.0,19.0,14.0,23.0,3.0,9.0,18.0,14.0,17.0,14.0,22.0,20.0,2023-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97674,22021,1630530,22100059,"OCT 27, 2021",L,26,3,7,0.429,2,4,0.500,0,0,0.0,1,2,3,0,0,0,2,1,8,5,1,2021,NOP,ATL,False,1610612740,1610612737,New Orleans Pelicans,0.439,1.0,20.0,20.0,20.0,19.0,19.0,16.0,23.0,28.0,24.0,27.0,2.0,6.0,10.0,3.0,24.0,11.0,13.0,17.0,7.0,26.0,16.0,14.0,4.0,21.0,21.0,2021-22,1.610613e+09,Atlanta Hawks,0.524,1.0,16.0,16.0,16.0,30.0,11.0,13.0,7.0,11.0,18.0,2.0,3.0,11.0,4.0,17.0,17.0,20.0,15.0,1.0,22.0,23.0,10.0,7.0,6.0,6.0,14.0,2021-22
97675,22021,1630530,22100047,"OCT 25, 2021",W,20,2,4,0.500,2,4,0.500,0,0,0.0,1,2,3,0,1,0,0,1,6,9,1,2021,NOP,MIN,True,1610612740,1610612750,New Orleans Pelicans,0.439,1.0,20.0,20.0,20.0,19.0,19.0,16.0,23.0,28.0,24.0,27.0,2.0,6.0,10.0,3.0,24.0,11.0,13.0,17.0,7.0,26.0,16.0,14.0,4.0,21.0,21.0,2021-22,1.610613e+09,Minnesota Timberwolves,0.561,1.0,12.0,12.0,12.0,13.0,10.0,5.0,22.0,1.0,1.0,12.0,4.0,8.0,14.0,6.0,25.0,16.0,7.0,21.0,3.0,3.0,19.0,29.0,2.0,1.0,9.0,2021-22
97676,22021,1630530,22100031,"OCT 23, 2021",L,22,2,5,0.400,2,5,0.400,0,0,0.0,0,5,5,0,1,0,0,3,6,4,1,2021,NOP,MIN,True,1610612740,1610612750,New Orleans Pelicans,0.439,1.0,20.0,20.0,20.0,19.0,19.0,16.0,23.0,28.0,24.0,27.0,2.0,6.0,10.0,3.0,24.0,11.0,13.0,17.0,7.0,26.0,16.0,14.0,4.0,21.0,21.0,2021-22,1.610613e+09,Minnesota Timberwolves,0.561,1.0,12.0,12.0,12.0,13.0,10.0,5.0,22.0,1.0,1.0,12.0,4.0,8.0,14.0,6.0,25.0,16.0,7.0,21.0,3.0,3.0,19.0,29.0,2.0,1.0,9.0,2021-22
97677,22021,1630530,22100022,"OCT 22, 2021",L,25,2,5,0.400,1,3,0.333,0,1,0.0,0,2,2,1,0,0,2,2,5,-28,1,2021,NOP,CHI,True,1610612740,1610612741,New Orleans Pelicans,0.439,1.0,20.0,20.0,20.0,19.0,19.0,16.0,23.0,28.0,24.0,27.0,2.0,6.0,10.0,3.0,24.0,11.0,13.0,17.0,7.0,26.0,16.0,14.0,4.0,21.0,21.0,2021-22,1.610613e+09,Chicago Bulls,0.561,1.0,12.0,12.0,12.0,24.0,7.0,20.0,3.0,29.0,30.0,4.0,9.0,17.0,3.0,29.0,22.0,28.0,19.0,6.0,23.0,25.0,24.0,8.0,28.0,13.0,20.0,2021-22
97678,22021,1630530,22100009,"OCT 20, 2021",L,18,2,7,0.286,2,5,0.400,0,0,0.0,0,0,0,2,0,0,0,1,6,-4,1,2021,NOP,PHI,False,1610612740,1610612755,New Orleans Pelicans,0.439,1.0,20.0,20.0,20.0,19.0,19.0,16.0,23.0,28.0,24.0,27.0,2.0,6.0,10.0,3.0,24.0,11.0,13.0,17.0,7.0,26.0,16.0,14.0,4.0,21.0,21.0,2021-22,1.610613e+09,Philadelphia 76ers,0.622,1.0,6.0,6.0,6.0,8.0,23.0,30.0,16.0,22.0,27.0,7.0,1.0,3.0,1.0,30.0,19.0,29.0,21.0,4.0,9.0,6.0,13.0,12.0,19.0,18.0,10.0,2021-22

# Drop unnecessary columns

In [153]:
cols_to_drop = ['WL', 'GAME_DATE', 'Game_ID']
all_games_df.drop(columns=cols_to_drop, inplace=True)

In [154]:
all_games_df

,SEASON_ID,Player_ID,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,YEAR,TEAM,RIVAL,AWAY,TEAM_ID,RIVAL_ID,TEAM_NAME,TEAM_W_PCT,TEAM_GP_RANK,TEAM_W_RANK,TEAM_L_RANK,TEAM_W_PCT_RANK,TEAM_MIN_RANK,TEAM_FGM_RANK,TEAM_FGA_RANK,TEAM_FG_PCT_RANK,TEAM_FG3M_RANK,TEAM_FG3A_RANK,TEAM_FG3_PCT_RANK,TEAM_FTM_RANK,TEAM_FTA_RANK,TEAM_FT_PCT_RANK,TEAM_OREB_RANK,TEAM_DREB_RANK,TEAM_REB_RANK,TEAM_AST_RANK,TEAM_TOV_RANK,TEAM_STL_RANK,TEAM_BLK_RANK,TEAM_BLKA_RANK,TEAM_PF_RANK,TEAM_PFD_RANK,TEAM_PTS_RANK,TEAM_PLUS_MINUS_RANK,TEAM_SEASON,RIVAL_TEAM_ID,RIVAL_NAME,RIVAL_W_PCT,RIVAL_GP_RANK,RIVAL_W_RANK,RIVAL_L_RANK,RIVAL_W_PCT_RANK,RIVAL_MIN_RANK,RIVAL_FGM_RANK,RIVAL_FGA_RANK,RIVAL_FG_PCT_RANK,RIVAL_FG3M_RANK,RIVAL_FG3A_RANK,RIVAL_FG3_PCT_RANK,RIVAL_FTM_RANK,RIVAL_FTA_RANK,RIVAL_FT_PCT_RANK,RIVAL_OREB_RANK,RIVAL_DREB_RANK,RIVAL_REB_RANK,RIVAL_AST_RANK,RIVAL_TOV_RANK,RIVAL_STL_RANK,RIVAL_BLK_RANK,RIVAL_BLKA_RANK,RIVAL_PF_RANK,RIVAL_PFD_RANK,RIVAL_PTS_RANK,RIVAL_PLUS_MINUS_RANK,RIVAL_SEASON
0,22023,1630173,19,2,3,0.667,0,0,0.000,0,0,0.0,1,4,5,2,0,1,2,3,4,-2,1,2024,NYK,CHI,False,1610612752,1610612741,New York Knicks,0.610,1.0,6.0,6.0,6.0,23.0,22.0,18.0,20.0,10.0,13.0,14.0,16.0,14.0,16.0,1.0,21.0,5.0,29.0,15.0,17.0,29.0,20.0,6.0,10.0,19.0,5.0,2023-24,1.610613e+09,Chicago Bulls,0.476,1.0,20.0,20.0,20.0,1.0,16.0,13.0,18.0,27.0,26.0,20.0,17.0,18.0,10.0,8.0,19.0,14.0,23.0,3.0,9.0,18.0,14.0,17.0,14.0,22.0,20.0,2023-24
1,22023,1630173,8,2,2,1.000,1,1,1.000,0,0,0.0,0,3,3,0,0,0,0,0,5,3,1,2024,NYK,BKN,False,1610612752,1610612751,New York Knicks,0.610,1.0,6.0,6.0,6.0,23.0,22.0,18.0,20.0,10.0,13.0,14.0,16.0,14.0,16.0,1.0,21.0,5.0,29.0,15.0,17.0,29.0,20.0,6.0,10.0,19.0,5.0,2023-24,1.610613e+09,Brooklyn Nets,0.390,1.0,22.0,22.0,22.0,10.0,25.0,16.0,28.0,9.0,9.0,19.0,23.0,20.0,28.0,7.0,20.0,11.0,20.0,12.0,28.0,12.0,16.0,13.0,21.0,25.0,22.0,2023-24
2,22023,1630173,16,1,6,0.167,0,1,0.000,0,0,0.0,2,3,5,0,0,1,1,0,2,-9,1,2024,NYK,BOS,True,1610612752,1610612738,New York Knicks,0.610,1.0,6.0,6.0,6.0,23.0,22.0,18.0,20.0,10.0,13.0,14.0,16.0,14.0,16.0,1.0,21.0,5.0,29.0,15.0,17.0,29.0,20.0,6.0,10.0,19.0,5.0,2023-24,1.610613e+09,Boston Celtics,0.780,1.0,1.0,1.0,1.0,7.0,4.0,8.0,8.0,1.0,1.0,2.0,19.0,26.0,7.0,14.0,1.0,2.0,14.0,1.0,27.0,1.0,1.0,2.0,30.0,2.0,1.0,2023-24
3,22023,1630173,5,0,1,0.000,0,0,0.000,0,0,0.0,0,0,0,0,0,0,0,1,0,5,1,2024,NYK,MIL,True,1610612752,1610612749,New York Knicks,0.610,1.0,6.0,6.0,6.0,23.0,22.0,18.0,20.0,10.0,13.0,14.0,16.0,14.0,16.0,1.0,21.0,5.0,29.0,15.0,17.0,29.0,20.0,6.0,10.0,19.0,5.0,2023-24,1.610613e+09,Milwaukee Bucks,0.598,1.0,8.0,8.0,8.0,10.0,8.0,19.0,7.0,5.0,5.0,11.0,7.0,3.0,19.0,24.0,3.0,9.0,17.0,9.0,26.0,15.0,3.0,21.0,9.0,4.0,11.0,2023-24
4,22023,1630173,19,0,2,0.000,0,1,0.000,0,0,0.0,1,3,4,1,1,0,1,4,0,-2,1,2024,NYK,CHI,True,1610612752,1610612741,New York Knicks,0.610,1.0,6.0,6.0,6.0,23.0,22.0,18.0,20.0,10.0,13.0,14.0,16.0,14.0,16.0,1.0,21.0,5.0,29.0,15.0,17.0,29.0,20.0,6.0,10.0,19.0,5.0,2023-24,1.610613e+09,Chicago Bulls,0.476,1.0,20.0,20.0,20.0,1.0,16.0,13.0,18.0,27.0,26.0,20.0,17.0,18.0,10.0,8.0,19.0,14.0,23.0,3.0,9.0,18.0,14.0,17.0,14.0,22.0,20.0,2023-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97674,22021,1630530,26,3,7,0.429,2,4,0.500,0,0,0.0,1,2,3,0,0,0,2,1,8,5,1,2021,NOP,ATL,False,1610612740,1610612737,New Orleans Pelicans,0.439,1.0,20.0,20.0,20.0,19.0,19.0,16.0,23.0,28.0,24.0,27.0,2.0,6.0,10.0,3.0,24.0,11.0,13.0,17.0,7.0,26.0,16.0,14.0,4.0,21.0,21.0,2021-22,1.610613e+09,Atlanta Hawks,0.524,1.0,16.0,16.0,16.0,30.0,11.0,13.0,7.0,11.0,18.0,2.0,3.0,11.0,4.0,17.0,17.0,20.0,15.0,1.0,22.0,23.0,10.0,7.0,6.0,6.0,14.0,2021-22
97675,22021,1630530,20,2,4,0.500,2,4,0.500,0,0,0.0,1,2,3,0,1,0,0,1,6,9,1,2021,NOP,MIN,True,1610612740,1610612750,New Orleans Pelicans,0.439,1.0,20.0,20.0,20.0,19.0,19.0,16.0,23.0,28.0,24.0,27.0,2.0,6.0,10.0,3.0,24.0,11.0,13.0,17.0,7.0,26.0,16.0,14.0,4.0,21.0,21.0,2021-22,1.610613e+09,Minnesota Timberwolves,0.561,1.0,12.0,12.0,12.0,13.0,10.0,5.0,22.0,1.0,1.0,12.0,4.0,8.0,14.0,6.0,25.0,16.0,7.0,21.0,3.0,3.0,19.0,29.0,2.0,1.0,9.0,2021-22
97676,22021,1630530,22,2,5,0.400,2,5,0.400,0,0,0.0,0,5,5,0,1,0,0,3,6,4,1,2021,NOP,MIN,True,1610612740,1610612750,New Orleans Pelicans,0.439,1.0,20.0,20.0,20.0,19.0,19.0,16.0,23.0,28.0,24.0,27.0,2.0,6.0,10.0,3.0,24.0,11.0,13.0,17.0,7.0,26.0,16.0,14.0,4.0,21.0,21.0,2021-22,1.610613e+09,Minnesota Timberwolves,0.561,1.0,12.0,12.0,12.0,13.0,10.0,5.0,22.0,1.0,1.0,12.0,4.0,8.0,14.0,6.0,25.0,16.0,7.0,21.0,3.0,3.0,19.0,29.0,2.0,1.0,9.0,2021-22
97677,22021,1630530,25,2,5,0.400,1,3,0.333,0,1,0.0,0,2,2,1,0,0,2,2,5,-28,1,2021,NOP,CHI,True,1610612740,1610612741,New Orleans Pelicans,0.439,1.0,20.0,20.0,20.0,19.0,19.0,16.0,23.0,28.0,24.0,27.0,2.0,6.0,10.0,3.0,24.0,11.0,13.0,17.0,7.0,26.0,16.0,14.0,4.0,21.0,21.0,2021-22,1.610613e+09,Chicago Bulls,0.561,1.0,12.0,12.0,12.0,24.0,7.0,20.0,3.0,29.0,30.0,4.0,9.0,17.0,3.0,29.0,22.0,28.0,19.0,6.0,23.0,25.0,24.0,8.0,28.0,13.0,20.0,2021-22
97678,22021,1630530,18,2,7,0.286,2,5,0.400,0,0,0.0,0,0,0,2,0,0,0,1,6,-4,1,2021,NOP,PHI,False,1610612740,1610612755,New Orleans Pelicans,0.439,1.0,20.0,20.0,20.0,19.0,19.0,16.0,23.0,28.0,24.0,27.0,2.0,6.0,10.0,3.0,24.0,11.0,13.0,17.0,7.0,26.0,16.0,14.0,4.0,21.0,21.0,2021-22,1.610613e+09,Philadelphia 76ers,0.622,1.0,6.0,6.0,6.0,8.0,23.0,30.0,16.0,22.0,27.0,7.0,1.0,3.0,1.0,30.0,19.0,29.0,21.0,4.0,9.0,6.0,13.0,12.0,19.0,18.0,10.0,2021-22

In [67]:
all_games_df.dtypes

SEASON_ID                 int64
Player_ID                 int64
Game_ID                   int64
GAME_DATE                object
MIN                       int64
                          ...
RIVAL_TM_TOV_PCT_RANK     int64
RIVAL_EFG_PCT_RANK        int64
RIVAL_TS_PCT_RANK         int64
RIVAL_PACE_RANK           int64
RIVAL_PIE_RANK            int64
Length: 156, dtype: object

# Divide categorical and continuous columns

In [155]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

LE = LabelEncoder()
SS = StandardScaler()
categorical = ['TEAM', 'RIVAL', 'TEAM_NAME', 'RIVAL_NAME']
continuous = ['MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
       'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS', 'PLUS_MINUS']

for col in categorical:
    all_games_df[col] = LE.fit_transform(all_games_df[col])
for col in continuous:
    all_games_df[col] = SS.fit_transform(all_games_df[col].values.reshape(-1, 1))

In [156]:
all_games_df.isnull().sum()

SEASON_ID                    0
Player_ID                    0
MIN                          0
FGM                          0
FGA                          0
                         ...
RIVAL_PF_RANK            31872
RIVAL_PFD_RANK           31872
RIVAL_PTS_RANK           31872
RIVAL_PLUS_MINUS_RANK    31872
RIVAL_SEASON             31872
Length: 88, dtype: int64

# Take care of missing values

In [157]:
# Handle rank columns
rank_columns = [col for col in all_games_df.columns if 'RANK' in col]

for col in rank_columns:
    all_games_df[col].fillna(all_games_df[col].max() + 1, inplace=True)

for col in rank_columns:
    unique_ranks = sorted(all_games_df[col].unique(), reverse=True)
    all_games_df[col] = pd.Categorical(all_games_df[col], categories=unique_ranks, ordered=True)

/tmp/ipykernel_36/3965658069.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  all_games_df[col].fillna(all_games_df[col].max() + 1, inplace=True)

In [158]:
pd.options.display.max_rows = None
all_games_df.isnull().sum()

SEASON_ID                    0
Player_ID                    0
MIN                          0
FGM                          0
FGA                          0
FG_PCT                       0
FG3M                         0
FG3A                         0
FG3_PCT                      0
FTM                          0
FTA                          0
FT_PCT                       0
OREB                         0
DREB                         0
REB                          0
AST                          0
STL                          0
BLK                          0
TOV                          0
PF                           0
PTS                          0
PLUS_MINUS                   0
VIDEO_AVAILABLE              0
YEAR                         0
TEAM                         0
RIVAL                        0
AWAY                         0
TEAM_ID                      0
RIVAL_ID                     0
TEAM_NAME                    0
TEAM_W_PCT               31872
TEAM_GP_RANK                 0
TEAM_W_RANK                  0
TEAM_L_RANK                  0
TEAM_W_PCT_RANK              0
TEAM_MIN_RANK                0
TEAM_FGM_RANK                0
TEAM_FGA_RANK                0
TEAM_FG_PCT_RANK             0
TEAM_FG3M_RANK               0
TEAM_FG3A_RANK               0
TEAM_FG3_PCT_RANK            0
TEAM_FTM_RANK                0
TEAM_FTA_RANK                0
TEAM_FT_PCT_RANK             0
TEAM_OREB_RANK               0
TEAM_DREB_RANK               0
TEAM_REB_RANK                0
TEAM_AST_RANK                0
TEAM_TOV_RANK                0
TEAM_STL_RANK                0
TEAM_BLK_RANK                0
TEAM_BLKA_RANK               0
TEAM_PF_RANK                 0
TEAM_PFD_RANK                0
TEAM_PTS_RANK                0
TEAM_PLUS_MINUS_RANK         0
TEAM_SEASON              31872
RIVAL_TEAM_ID            31872
RIVAL_NAME                   0
RIVAL_W_PCT              31872
RIVAL_GP_RANK                0
RIVAL_W_RANK                 0
RIVAL_L_RANK                 0
RIVAL_W_PCT_RANK             0
RIVAL_MIN_RANK               0
RIVAL_FGM_RANK               0
RIVAL_FGA_RANK               0
RIVAL_FG_PCT_RANK            0
RIVAL_FG3M_RANK              0
RIVAL_FG3A_RANK              0
RIVAL_FG3_PCT_RANK           0
RIVAL_FTM_RANK               0
RIVAL_FTA_RANK               0
RIVAL_FT_PCT_RANK            0
RIVAL_OREB_RANK              0
RIVAL_DREB_RANK              0
RIVAL_REB_RANK               0
RIVAL_AST_RANK               0
RIVAL_TOV_RANK               0
RIVAL_STL_RANK               0
RIVAL_BLK_RANK               0
RIVAL_BLKA_RANK              0
RIVAL_PF_RANK                0
RIVAL_PFD_RANK               0
RIVAL_PTS_RANK               0
RIVAL_PLUS_MINUS_RANK        0
RIVAL_SEASON             31872
dtype: int64

In [159]:
# Handle the final three with missing values
cols_with_null = ['TEAM_W_PCT', 'RIVAL_TEAM_ID', 'RIVAL_W_PCT', 'RIVAL_SEASON']

# TEAM_W_PCT
winning_mode = all_games_df['TEAM_W_PCT'].mode()[0]
all_games_df['TEAM_W_PCT'].fillna(winning_mode, inplace=True)

# TEAM_SEASON
all_games_df['TEAM_SEASON'].fillna(-1, inplace=True)
# RIVAL_SEASON
all_games_df['RIVAL_SEASON'] = all_games_df['TEAM_SEASON']

# RIVAL_TEAM_ID
all_games_df['RIVAL_TEAM_ID'].fillna(-1, inplace=True)
                  

# RIVAL_W_PCT
rival_winning_mode = all_games_df['RIVAL_W_PCT'].mode()[0]
all_games_df['RIVAL_W_PCT'].fillna(rival_winning_mode, inplace=True)

/tmp/ipykernel_36/3900297137.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  all_games_df['TEAM_W_PCT'].fillna(winning_mode, inplace=True)
/tmp/ipykernel_36/3900297137.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  all_games_df['TEAM_SEASON'].fillna(-1, inplace=True)
/tmp/ipykernel_36/3900297137.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  all_games_df['RIVAL_TEAM_ID'].fillna(-1, inplace=True)
/tmp/ipykernel_36/3900297137.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  all_games_df['RIVAL_W_PCT'].fillna(rival_winning_mode, inplace=True)

In [160]:
# # Handle the final three with missing values
# cols_with_null = ['TEAM_W_PCT_x', 'TEAM_SEASON_x', 'RIVAL_TEAM_ID_x', 'RIVAL_W_PCT_x', 'RIVAL_SEASON_x']

# # TEAM_W_PCT
# winning_mode = all_games_df['TEAM_W_PCT_x'].mode()[0]
# all_games_df['TEAM_W_PCT_x'].fillna(winning_mode, inplace=True)

# # TEAM_SEASON_x
# all_games_df['TEAM_SEASON_x'].fillna(-1, inplace=True)
# all_games_df['RIVAL_SEASON_x'] = all_games_df['TEAM_SEASON_x']

# # RIVAL_TEAM_ID
# all_games_df['RIVAL_TEAM_ID_x'].fillna(-1, inplace=True)

# # RIVAL_W_PCT
# rival_winning_mode = all_games_df['RIVAL_W_PCT_x'].mode()[0]
# all_games_df['RIVAL_W_PCT_x'].fillna(rival_winning_mode, inplace=True)

In [161]:
all_games_df.isnull().sum()

SEASON_ID                0
Player_ID                0
MIN                      0
FGM                      0
FGA                      0
FG_PCT                   0
FG3M                     0
FG3A                     0
FG3_PCT                  0
FTM                      0
FTA                      0
FT_PCT                   0
OREB                     0
DREB                     0
REB                      0
AST                      0
STL                      0
BLK                      0
TOV                      0
PF                       0
PTS                      0
PLUS_MINUS               0
VIDEO_AVAILABLE          0
YEAR                     0
TEAM                     0
RIVAL                    0
AWAY                     0
TEAM_ID                  0
RIVAL_ID                 0
TEAM_NAME                0
TEAM_W_PCT               0
TEAM_GP_RANK             0
TEAM_W_RANK              0
TEAM_L_RANK              0
TEAM_W_PCT_RANK          0
TEAM_MIN_RANK            0
TEAM_FGM_RANK            0
TEAM_FGA_RANK            0
TEAM_FG_PCT_RANK         0
TEAM_FG3M_RANK           0
TEAM_FG3A_RANK           0
TEAM_FG3_PCT_RANK        0
TEAM_FTM_RANK            0
TEAM_FTA_RANK            0
TEAM_FT_PCT_RANK         0
TEAM_OREB_RANK           0
TEAM_DREB_RANK           0
TEAM_REB_RANK            0
TEAM_AST_RANK            0
TEAM_TOV_RANK            0
TEAM_STL_RANK            0
TEAM_BLK_RANK            0
TEAM_BLKA_RANK           0
TEAM_PF_RANK             0
TEAM_PFD_RANK            0
TEAM_PTS_RANK            0
TEAM_PLUS_MINUS_RANK     0
TEAM_SEASON              0
RIVAL_TEAM_ID            0
RIVAL_NAME               0
RIVAL_W_PCT              0
RIVAL_GP_RANK            0
RIVAL_W_RANK             0
RIVAL_L_RANK             0
RIVAL_W_PCT_RANK         0
RIVAL_MIN_RANK           0
RIVAL_FGM_RANK           0
RIVAL_FGA_RANK           0
RIVAL_FG_PCT_RANK        0
RIVAL_FG3M_RANK          0
RIVAL_FG3A_RANK          0
RIVAL_FG3_PCT_RANK       0
RIVAL_FTM_RANK           0
RIVAL_FTA_RANK           0
RIVAL_FT_PCT_RANK        0
RIVAL_OREB_RANK          0
RIVAL_DREB_RANK          0
RIVAL_REB_RANK           0
RIVAL_AST_RANK           0
RIVAL_TOV_RANK           0
RIVAL_STL_RANK           0
RIVAL_BLK_RANK           0
RIVAL_BLKA_RANK          0
RIVAL_PF_RANK            0
RIVAL_PFD_RANK           0
RIVAL_PTS_RANK           0
RIVAL_PLUS_MINUS_RANK    0
RIVAL_SEASON             0
dtype: int64

# Prepare the training and validation datasets

In [162]:
from sklearn.model_selection import train_test_split

y = all_games_df[continuous].copy()
X = all_games_df.drop(columns=list(y.columns))

# Apply pd.get_dummies to the selected columns
dummyColumns = ['TEAM_SEASON', 'RIVAL_SEASON']
encoded_df = pd.get_dummies(all_games_df[dummyColumns], drop_first=True)

# Concatenate the original DataFrame with the encoded columns
X = pd.concat([X.drop(columns=dummyColumns), encoded_df], axis=1)

X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state=42)

In [163]:
pd.options.display.max_rows = 10
X_train

,SEASON_ID,Player_ID,VIDEO_AVAILABLE,YEAR,TEAM,RIVAL,AWAY,TEAM_ID,RIVAL_ID,TEAM_NAME,TEAM_W_PCT,TEAM_GP_RANK,TEAM_W_RANK,TEAM_L_RANK,TEAM_W_PCT_RANK,TEAM_MIN_RANK,TEAM_FGM_RANK,TEAM_FGA_RANK,TEAM_FG_PCT_RANK,TEAM_FG3M_RANK,TEAM_FG3A_RANK,TEAM_FG3_PCT_RANK,TEAM_FTM_RANK,TEAM_FTA_RANK,TEAM_FT_PCT_RANK,TEAM_OREB_RANK,TEAM_DREB_RANK,TEAM_REB_RANK,TEAM_AST_RANK,TEAM_TOV_RANK,TEAM_STL_RANK,TEAM_BLK_RANK,TEAM_BLKA_RANK,TEAM_PF_RANK,TEAM_PFD_RANK,TEAM_PTS_RANK,TEAM_PLUS_MINUS_RANK,RIVAL_TEAM_ID,RIVAL_NAME,RIVAL_W_PCT,RIVAL_GP_RANK,RIVAL_W_RANK,RIVAL_L_RANK,RIVAL_W_PCT_RANK,RIVAL_MIN_RANK,RIVAL_FGM_RANK,RIVAL_FGA_RANK,RIVAL_FG_PCT_RANK,RIVAL_FG3M_RANK,RIVAL_FG3A_RANK,RIVAL_FG3_PCT_RANK,RIVAL_FTM_RANK,RIVAL_FTA_RANK,RIVAL_FT_PCT_RANK,RIVAL_OREB_RANK,RIVAL_DREB_RANK,RIVAL_REB_RANK,RIVAL_AST_RANK,RIVAL_TOV_RANK,RIVAL_STL_RANK,RIVAL_BLK_RANK,RIVAL_BLKA_RANK,RIVAL_PF_RANK,RIVAL_PFD_RANK,RIVAL_PTS_RANK,RIVAL_PLUS_MINUS_RANK,TEAM_SEASON_2019-20,TEAM_SEASON_2020-21,TEAM_SEASON_2021-22,TEAM_SEASON_2022-23,TEAM_SEASON_2023-24,RIVAL_SEASON_2019-20,RIVAL_SEASON_2020-21,RIVAL_SEASON_2021-22,RIVAL_SEASON_2022-23,RIVAL_SEASON_2023-24
41351,22018,1628365,1,2018,22,4,False,1610612755,1610612741,30,0.573,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,-1.000000e+00,30,0.573,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,False,False,False,False,False,False,False,False,False,False
30035,22014,203109,1,2015,2,4,False,1610612738,1610612741,30,0.573,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,-1.000000e+00,30,0.573,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,False,False,False,False,False,False,False,False,False,False
13969,22018,202711,1,2019,11,22,True,1610612754,1610612755,30,0.573,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,-1.000000e+00,30,0.573,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,False,False,False,False,False,False,False,False,False,False
50221,22019,201145,1,2020,10,14,False,1610612745,1610612763,10,0.611,11.0,8.0,7.0,8.0,16.0,16.0,7.0,22.0,2.0,1.0,24.0,2.0,2.0,8.0,16.0,18.0,16.0,24.0,19.0,3.0,10.0,18.0,25.0,11.0,4.0,8.0,1.610613e+09,14,0.466,3.0,16.0,15.0,16.0,9.0,4.0,4.0,7.0,20.0,19.0,23.0,22.0,20.0,19.0,10.0,5.0,5.0,2.0,29.0,9.0,5.0,25.0,21.0,17.0,9.0,17.0,True,False,False,False,False,True,False,False,False,False
29736,22018,203109,1,2018,28,10,True,1610612762,1610612745,30,0.573,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,-1.000000e+00,30,0.573,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6265,22021,1628964,1,2022,21,4,False,1610612753,1610612741,21,0.268,1.0,29.0,29.0,29.0,13.0,28.0,14.0,28.0,15.0,11.0,28.0,28.0,29.0,11.0,27.0,7.0,14.0,20.0,25.0,28.0,20.0,27.0,14.0,27.0,29.0,27.0,1.610613e+09,4,0.561,1.0,12.0,12.0,12.0,24.0,7.0,20.0,3.0,29.0,30.0,4.0,9.0,17.0,3.0,29.0,22.0,28.0,19.0,6.0,23.0,25.0,24.0,8.0,28.0,13.0,20.0,False,False,True,False,False,False,False,True,False,False
54886,22018,202699,1,2018,12,17,False,1610612746,1610612750,30,0.573,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,-1.000000e+00,30,0.573,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,31.0,False,False,False,False,False,False,False,False,False,False
76820,22019,203897,1,2019,4,16,False,1610612741,1610612749,4,0.338,26.0,24.0,23.0,24.0,29.0,28.0,26.0,26.0,21.0,20.0,22.0,29.0,29.0,21.0,21.0,30.0,30.0,28.0,12.0,1.0,29.0,24.0,9.0,30.0,28.0,22.0,1.610613e+09,16,0.767,3.0,1.0,1.0,1.0,6.0,1.0,3.0,3.0,3.0,3.0,18.0,9.0,4.0,27.0,19.0,1.0,1.0,6.0,28.0,19.0,3.0,10.0,10.0,6.0,2.0,1.0,True,False,False,False,False,True,False,False,False,False
860,22022,1630534,1,2023,28,6,False,1610612762,1610612742,28,0.451,1.0,22.0,22.0,22.0,18.0,12.0,10.0,18.0,7.0,5.0,20.0,13.0,12.0,14.0,6.0,6.0,5.0,10.0,28.0,30.0,7.0,19.0,21.0,9.0,7.0,22.0,1.610613e+09,6,0.463,1.0,21.0,21.0,21.0,3.0,28.0,29.0,15.0,3.0,3.0,8.0,12.0,6.0,23.0,30.0,27.0,30.0,28.0,2.0,29.0,28.0,2.0,23.0,1.0,16.0,19.0,False,False,False,True,False,False,False,False,True,False
15795,22022,1631103,1,2023,26,29,False,1610612759,1610612764,26,0.268,1.0,28.0,28.0,28.0,8.0,6.0,1.0,25.0,22.0,20.0,26.0,30.0,29.0,28.0,7.0,23.0,12.0,5.0,26.0,22.0,26.0,25.0,12.0,29.0,23.0,30.0,1.610613e+09,29,0.427,1.0,23.0,23.0,23.0,25.0,14.0,20.0,8.0,21.0,23.0,18.0,22.0,22.0,15.0,24.0,5.0,15.0,14.0,16.0,23.0,9.0,20.0,5.0,24.0,21.0,23.0,False,False,False,True,False,False,False,False,True,False

In [164]:
pd.options.display.max_rows = 136
X_train.dtypes == 'object'

SEASON_ID                False
Player_ID                False
VIDEO_AVAILABLE          False
YEAR                     False
TEAM                     False
RIVAL                    False
AWAY                     False
TEAM_ID                  False
RIVAL_ID                 False
TEAM_NAME                False
TEAM_W_PCT               False
TEAM_GP_RANK             False
TEAM_W_RANK              False
TEAM_L_RANK              False
TEAM_W_PCT_RANK          False
TEAM_MIN_RANK            False
TEAM_FGM_RANK            False
TEAM_FGA_RANK            False
TEAM_FG_PCT_RANK         False
TEAM_FG3M_RANK           False
TEAM_FG3A_RANK           False
TEAM_FG3_PCT_RANK        False
TEAM_FTM_RANK            False
TEAM_FTA_RANK            False
TEAM_FT_PCT_RANK         False
TEAM_OREB_RANK           False
TEAM_DREB_RANK           False
TEAM_REB_RANK            False
TEAM_AST_RANK            False
TEAM_TOV_RANK            False
TEAM_STL_RANK            False
TEAM_BLK_RANK            False
TEAM_BLKA_RANK           False
TEAM_PF_RANK             False
TEAM_PFD_RANK            False
TEAM_PTS_RANK            False
TEAM_PLUS_MINUS_RANK     False
RIVAL_TEAM_ID            False
RIVAL_NAME               False
RIVAL_W_PCT              False
RIVAL_GP_RANK            False
RIVAL_W_RANK             False
RIVAL_L_RANK             False
RIVAL_W_PCT_RANK         False
RIVAL_MIN_RANK           False
RIVAL_FGM_RANK           False
RIVAL_FGA_RANK           False
RIVAL_FG_PCT_RANK        False
RIVAL_FG3M_RANK          False
RIVAL_FG3A_RANK          False
RIVAL_FG3_PCT_RANK       False
RIVAL_FTM_RANK           False
RIVAL_FTA_RANK           False
RIVAL_FT_PCT_RANK        False
RIVAL_OREB_RANK          False
RIVAL_DREB_RANK          False
RIVAL_REB_RANK           False
RIVAL_AST_RANK           False
RIVAL_TOV_RANK           False
RIVAL_STL_RANK           False
RIVAL_BLK_RANK           False
RIVAL_BLKA_RANK          False
RIVAL_PF_RANK            False
RIVAL_PFD_RANK           False
RIVAL_PTS_RANK           False
RIVAL_PLUS_MINUS_RANK    False
TEAM_SEASON_2019-20      False
TEAM_SEASON_2020-21      False
TEAM_SEASON_2021-22      False
TEAM_SEASON_2022-23      False
TEAM_SEASON_2023-24      False
RIVAL_SEASON_2019-20     False
RIVAL_SEASON_2020-21     False
RIVAL_SEASON_2021-22     False
RIVAL_SEASON_2022-23     False
RIVAL_SEASON_2023-24     False
dtype: bool

# Training the different models

In [165]:
from sklearn.linear_model import MultiTaskElasticNet
from sklearn.linear_model import MultiTaskLasso

# Create and train the multi-target regression model (ElasticNet)
multioutput_model = MultiOutputRegressor(
    ElasticNet(alpha=0.5, l1_ratio=0.5), n_jobs=5)
multioutput_model.fit(X_train, y_train)

# multioutput_model = MultiTaskLasso(alpha=0.5)
# multioutput_model.fit(X_train, y_train)

MultiOutputRegressor(estimator=ElasticNet(alpha=0.5), n_jobs=5)

# Predicting

In [166]:
# Multioutput predictions
multioutput_preds = multioutput_model.predict(X_valid)

# Print the error for each variable

In [167]:
# Unscale the predictions as we used StandardScaler to make the difference between variable value range null
multioutput_preds = SS.inverse_transform(multioutput_preds)

In [168]:
multioutputs_mae = []
for i in range(len(continuous)):
#     tree_mae = mean_absolute_error(y_valid.iloc[:, i], tree_preds[:, i])
#     trees_mae.append(tree_mae)
#     print(f"TREE_MAE for {continuous[i]}: {tree_mae}")
    multioutput_mae = mean_absolute_error(y_valid.iloc[:, i], multioutput_preds[:, i])
    multioutputs_mae.append(multioutput_mae)
    print(f"MULTIOUTPUT_MAE for {continuous[i]}: {multioutput_mae}")
#     forest_mae = mean_absolute_error(y_valid.iloc[:, i], forest_preds[:, i])
#     forests_mae.append(forest_mae)
#     print(f"FOREST_MAE for {continuous[i]}: {forest_mae}")
    print(f"-----------------------------------------------------")

MULTIOUTPUT_MAE for MIN: 2.8346346092638885
-----------------------------------------------------
MULTIOUTPUT_MAE for FGM: 2.14685619838897
-----------------------------------------------------
MULTIOUTPUT_MAE for FGA: 2.390950397693528
-----------------------------------------------------
MULTIOUTPUT_MAE for FG_PCT: 1.0060974165525658
-----------------------------------------------------
MULTIOUTPUT_MAE for FG3M: 1.506483475017383
-----------------------------------------------------
MULTIOUTPUT_MAE for FG3A: 1.7352460438079658
-----------------------------------------------------
MULTIOUTPUT_MAE for FG3_PCT: 1.0578859232742037
-----------------------------------------------------
MULTIOUTPUT_MAE for FTM: 2.050989395796241
-----------------------------------------------------
MULTIOUTPUT_MAE for FTA: 2.051968165655379
-----------------------------------------------------
MULTIOUTPUT_MAE for FT_PCT: 1.4864510950105139
-----------------------------------------------------
MULTIOUTPUT_MAE for OREB: 0.9874723710346003
-----------------------------------------------------
MULTIOUTPUT_MAE for DREB: 1.8457745834286146
-----------------------------------------------------
MULTIOUTPUT_MAE for REB: 1.6729751722636153
-----------------------------------------------------
MULTIOUTPUT_MAE for AST: 1.851935899579549
-----------------------------------------------------
MULTIOUTPUT_MAE for STL: 1.2925812607164564
-----------------------------------------------------
MULTIOUTPUT_MAE for BLK: 1.1175808477387976
-----------------------------------------------------
MULTIOUTPUT_MAE for TOV: 1.7523745674378934
-----------------------------------------------------
MULTIOUTPUT_MAE for PF: 1.1758277120901621
-----------------------------------------------------
MULTIOUTPUT_MAE for PTS: 2.3654594954247172
-----------------------------------------------------
MULTIOUTPUT_MAE for PLUS_MINUS: 1.815922746214106
-----------------------------------------------------

# Let's check the feature importance and keep the ones over 0.005

In [170]:
to_keep = feature_importance[feature_importance.imp > 0.005].cols
len(to_keep)

39

In [171]:
X_to_keep = X_train[to_keep]
X_to_valid = X_valid[to_keep]

In [172]:
from sklearn.linear_model import MultiTaskElasticNet
from sklearn.linear_model import MultiTaskLasso

# Create and train the multi-target regression model (ElasticNet)
multioutput_model = MultiOutputRegressor(
    ElasticNet(alpha=0.5, l1_ratio=0.5), n_jobs=5)
multioutput_model.fit(X_to_keep, y_train)

# multioutput_model = MultiTaskLasso(alpha=0.5)
# multioutput_model.fit(X_train, y_train)

MultiOutputRegressor(estimator=ElasticNet(alpha=0.5), n_jobs=5)

In [173]:
multioutput_preds = multioutput_model.predict(X_to_valid)
multioutput_preds = SS.inverse_transform(multioutput_preds)

In [174]:
multioutputs_mae = []
for i in range(len(continuous)):
    multioutput_mae = mean_absolute_error(y_valid.iloc[:, i], multioutput_preds[:, i])
    multioutputs_mae.append(multioutput_mae)
    print(f"MULTIOUTPUT_MAE for {continuous[i]}: {multioutput_mae}")
    print(f"-----------------------------------------------------")

MULTIOUTPUT_MAE for MIN: 2.8316601664582413
-----------------------------------------------------
MULTIOUTPUT_MAE for FGM: 2.1459363165872394
-----------------------------------------------------
MULTIOUTPUT_MAE for FGA: 2.3909446368666063
-----------------------------------------------------
MULTIOUTPUT_MAE for FG_PCT: 1.0026251801030908
-----------------------------------------------------
MULTIOUTPUT_MAE for FG3M: 1.5263608436381422
-----------------------------------------------------
MULTIOUTPUT_MAE for FG3A: 1.7490310887872191
-----------------------------------------------------
MULTIOUTPUT_MAE for FG3_PCT: 1.0422946913274391
-----------------------------------------------------
MULTIOUTPUT_MAE for FTM: 2.0519862996558436
-----------------------------------------------------
MULTIOUTPUT_MAE for FTA: 2.052502129182723
-----------------------------------------------------
MULTIOUTPUT_MAE for FT_PCT: 1.4988057269775006
-----------------------------------------------------
MULTIOUTPUT_MAE for OREB: 0.9798991082557041
-----------------------------------------------------
MULTIOUTPUT_MAE for DREB: 1.8464688989707057
-----------------------------------------------------
MULTIOUTPUT_MAE for REB: 1.6722359017801676
-----------------------------------------------------
MULTIOUTPUT_MAE for AST: 1.8478217827121945
-----------------------------------------------------
MULTIOUTPUT_MAE for STL: 1.2480673940555553
-----------------------------------------------------
MULTIOUTPUT_MAE for BLK: 1.1203622508880162
-----------------------------------------------------
MULTIOUTPUT_MAE for TOV: 1.729208761912785
-----------------------------------------------------
MULTIOUTPUT_MAE for PF: 1.1477902914349933
-----------------------------------------------------
MULTIOUTPUT_MAE for PTS: 2.3638691130730938
-----------------------------------------------------
MULTIOUTPUT_MAE for PLUS_MINUS: 1.6394930815747515
-----------------------------------------------------

In [ ]:
with open('multioutput_regressor_model.pkl', 'wb') as f:
    pickle.dump(model, f)